mode: "server"
network:
  interface: "tun0"
  address: "10.0.0.1/24"
  mtu: 1500

tunnel:
  certFile: "/etc/sssonector/certs/server.crt"
  keyFile: "/etc/sssonector/certs/server.key"
  caFile: "/etc/sssonector/certs/client.crt"
  listenAddress: "192.168.50.210"
  listenPort: 8443
  maxClients: 10
  uploadKbps: 10240
  downloadKbps: 10240

monitor:
  logFile: "/var/log/sssonector/server.log"
  snmpEnabled: false
  snmpPort: 161
  snmpCommunity: "public"
