# Server configuration for SSSonector

# Mode can be "server" or "client"
mode: "server"

# Network interface configuration
network:
  interface: "tun0"
  address: "10.0.0.1"
  mtu: 1500

# Tunnel configuration
tunnel:
  # Certificate configuration
  cert_file: "/etc/sssonector/certs/server.crt"
  key_file: "/etc/sssonector/certs/server.key"
  ca_file: "/etc/sssonector/certs/ca.crt"

  # Server settings
  listen_address: "0.0.0.0"
  listen_port: 8443
  max_clients: 100

  # Bandwidth throttling (bytes per second, 0 for unlimited)
  bandwidth_limit: 0

# Monitoring configuration
monitor:
  log_file: "/var/log/sssonector/server.log"
  log_level: "info"

  # SNMP monitoring
  snmp_enabled: true
  snmp_address: "0.0.0.0"
  snmp_port: 161
  snmp_community: "public"
