mode: "server"

network:
  interface: "tun0"
  address: "10.0.0.1/24"
  mtu: 1500

tunnel:
  cert_file: "/etc/sssonector/certs/server.crt"
  key_file: "/etc/sssonector/certs/server.key"
  ca_file: "/etc/sssonector/certs/client.crt"
  listen_address: "0.0.0.0"
  listen_port: 8443
  max_clients: 10
  retry_attempts: 3
  retry_interval: 5
  upload_kbps: 10240    # 10 Mbps
  download_kbps: 10240  # 10 Mbps
  bandwidth_limit: 10485760  # 10 MB/s

monitor:
  log_file: "/var/log/sssonector/server.log"
  log_level: "info"
  snmp_enabled: true
  snmp_address: "0.0.0.0"
  snmp_port: 161
  snmp_community: "public"

logging:
  level: "info"
  file_path: "/var/log/sssonector/server.log"
  max_size: 100  # MB

throttle:
  upload_kbps: 10240    # 10 Mbps
  download_kbps: 10240  # 10 Mbps
