mode: "server"

network:
  interface: "tun0"
  address: "10.0.0.1/24"
  mtu: 1500

tunnel:
  cert_file: "/etc/sssonector/certs/server.crt"
  key_file: "/etc/sssonector/certs/server.key"
  ca_file: "/etc/sssonector/certs/ca.crt"
  listen_address: "0.0.0.0"
  listen_port: 8443
  max_clients: 10
  upload_kbps: 10240
  download_kbps: 10240

monitor:
  log_file: "/var/log/sssonector/server.log"
  snmp_enabled: false
  snmp_port: 161
  snmp_community: "public"
