mode: "server"

network:
  interface: "tun0"
  address: "10.0.0.1/24"
  mtu: 1500

tunnel:
  cert_file: "certs/server.crt"
  key_file: "certs/server.key"
  ca_file: "certs/ca.crt"
  listen_address: "0.0.0.0"
  listen_port: 8443
  max_clients: 10
  upload_kbps: 10240
  download_kbps: 10240

monitor:
  log_file: "server.log"
  snmp_enabled: true
  snmp_port: 10161
  snmp_community: "public"
  snmp_address: "0.0.0.0"
