type: server
config:
  mode: server
  logging:
    level: debug
    file: /var/log/sssonector/server.log
    format: json
  network:
    name: tun0
    interface: tun0
    mtu: 1500
    address: 10.0.0.1/24
  tunnel:
    listen_address: 0.0.0.0
    listen_port: 8443
    protocol: tcp
    compression: false
  security:
    tls:
      min_version: "1.2"
      max_version: "1.3"
    auth_method: certificate
    cert_rotation:
      enabled: false
  monitor:
    enabled: true
    type: prometheus
    interval: 10s
    prometheus:
      enabled: true
      port: 9090
      path: /metrics
  metrics:
    enabled: true
    interval: 5s
    buffer_size: 1000
throttle:
  enabled: false
  rate: 1048576
  burst: 104858
metadata:
  version: 1.0.0
  environment: qa
  region: local
