#!/usr/bin/expect -f

set timeout 60
set password [lindex $argv 0]

# SSH into monitor server
spawn ssh 192.168.50.212

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "$ " { }
    ":~$ " { }
    "~$ " { }
}

# Update and install packages
send "sudo apt-get update\r"
expect {
    "password" {
        send "$password\r"
        exp_continue
    }
    "$ " { }
    ":~$ " { }
    "~$ " { }
}

send "sudo apt-get install -y snmpd snmp snmp-mibs-downloader\r"
expect {
    "$ " { }
    ":~$ " { }
    "~$ " { }
}

# Verify installation
send "dpkg -l | grep snmp\r"
expect {
    "$ " { }
    ":~$ " { }
    "~$ " { }
}

send "exit\r"
expect eof
