#!/usr/bin/expect -f

set timeout 20

# First SSH connection
spawn ssh 192.168.50.212
expect "password:"
send "101abn\r"
expect "$ "

# Install SNMP
send "sudo apt-get install -y snmp snmpd\r"
expect "password for sblanken:"
send "101abn\r"
expect "$ "

# Check SNMP status
send "sudo systemctl status snmpd\r"
expect "password for sblanken:"
send "101abn\r"
expect "$ "

# Exit
send "exit\r"
expect eof
